# Check the actual template against the parser used by CMake's bundle deployment.
set(MACOSX_BUNDLE_EXECUTABLE_NAME Afterimage)
set(MACOSX_BUNDLE_SHORT_VERSION_STRING 0.1.0)
set(MACOSX_BUNDLE_BUNDLE_VERSION 0.1.0)
set(CMAKE_OSX_DEPLOYMENT_TARGET 26.0)
set(app "${TEST_BINARY_DIR}/plist-fixture/Afterimage.app")
file(MAKE_DIRECTORY "${app}/Contents/MacOS")
file(WRITE "${app}/Contents/MacOS/Afterimage" "fixture")
configure_file("${SOURCE_DIR}/src/Info.plist.in" "${app}/Contents/Info.plist" @ONLY)
include(BundleUtilities)
get_bundle_main_executable("${app}" executable)
if(NOT executable STREQUAL "${app}/Contents/MacOS/Afterimage")
  message(FATAL_ERROR "Bundle executable metadata cannot be read: ${executable}")
endif()
message(STATUS "macOS plist executable metadata verified")
